### ISSUE TITLE
Tests fail for /movies implementation

### ISSUE THREAD

**Issue by qnkxsovc** [mdnls/hh-app#1]
The tests specified for the [movies top level route](https://github.com/qnkxsovc/hh-app/blob/master/test/controller/movies.test.ts) are currently failing. 

Please implement the functionality [here](https://github.com/qnkxsovc/hh-app/blob/master/src/controller/movies.ts) to make these tests pass.

**Comment by rhart14** [comment]
I don't think this is actually gonna be done lol
