### ISSUE TITLE
Tests fail for /recipes implementation

### ISSUE THREAD

**Issue by qnkxsovc** [mdnls/hh-app#2]
The tests specified for the [recipes top level route](https://github.com/qnkxsovc/hh-app/blob/master/test/controller/recipes.test.ts) are currently failing. 

Please implement the functionality [here](https://github.com/qnkxsovc/hh-app/blob/master/src/controller/recipes.ts) to make these tests pass.

**Comment by rhart14** [comment]
I don't think this is actually gonna be done lol
